### ISSUE TITLE
hexo 4.2.0 使用该主题访问报错

### ISSUE THREAD

**Issue by Qznan** [codefine/hexo-theme-mellow#54]
用hexo默认的landscape主题正常访问，但是切换成mellow主题后，启动正常，但访问不了，报错信息如下:
Unhandled rejection TypeError: /Users/yonas/blog/themes/mellow/layout/index.ejs:8

    6     <div class="container body-wrap">
    7         <ul class="post-list">
    8         <%
    9         if (theme.articleSort) {
    10             site.posts.data = site.posts.data.sort(function(a, b) {
    11                 return Number(a.updated.format('x')) < Number(b.updated.format('x')) ? 1 : -1;

Cannot read property 'per_page' of undefined
    at eval (/Users/yonas/blog/themes/mellow/layout/index.ejs:26:49)
    at index (/Users/yonas/blog/node_modules/ejs/lib/ejs.js:682:17)
    at viewFn._compiled.locals [as _compiled] (/Users/yonas/blog/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/Users/yonas/blog/node_modules/hexo/lib/theme/view.js:41:15)
    at /Users/yonas/blog/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/Users/yonas/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/yonas/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/yonas/blog/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:470:10)
    at resume_ (_stream_readable.js:949:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

环境信息如下:
hexo version
hexo: 4.2.0
hexo-cli: 3.0.0
os: Darwin 17.5.0 darwin x64
http_parser: 2.8.0
node: 10.16.3
v8: 6.8.275.32-node.54
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 64
nghttp2: 1.39.2
napi: 4
openssl: 1.1.1c
icu: 64.2
unicode: 12.1
cldr: 35.1
tz: 2019a

cat package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0"
  }

**Comment by ITCJ** [comment]
> 用hexo默认的landscape主题正常访问，但是切换成mellow主题后，启动正常，但访问不了，报错信息如下:
> Unhandled rejection TypeError: /Users/yonas/blog/themes/mellow/layout/index.ejs:8
> 
> ```
> 6     <div class="container body-wrap">
> 7         <ul class="post-list">
> 8         <%
> 9         if (theme.articleSort) {
> 10             site.posts.data = site.posts.data.sort(function(a, b) {
> 11                 return Number(a.updated.format('x')) < Number(b.updated.format('x')) ? 1 : -1;
> ```
> 
> Cannot read property 'per_page' of undefined
> at eval (/Users/yonas/blog/themes/mellow/layout/index.ejs:26:49)
> at index (/Users/yonas/blog/node_modules/ejs/lib/ejs.js:682:17)
> at viewFn._compiled.locals [as _compiled] (/Users/yonas/blog/node_modules/hexo/lib/theme/view.js:136:48)
> at viewFn.View.render (/Users/yonas/blog/node_modules/hexo/lib/theme/view.js:41:15)
> at /Users/yonas/blog/node_modules/hexo/lib/hexo/index.js:61:21
> at tryCatcher (/Users/yonas/blog/node_modules/bluebird/js/release/util.js:16:23)
> at /Users/yonas/blog/node_modules/bluebird/js/release/method.js:15:34
> at RouteStream._read (/Users/yonas/blog/node_modules/hexo/lib/hexo/router.js:126:3)
> at RouteStream.Readable.read (_stream_readable.js:470:10) at resume_ (_stream_readable.js:949:12)
> at process._tickCallback (internal/process/next_tick.js:63:19)
> 
> 环境信息如下:
> hexo version
> hexo: 4.2.0
> hexo-cli: 3.0.0
> os: Darwin 17.5.0 darwin x64
> http_parser: 2.8.0
> node: 10.16.3
> v8: 6.8.275.32-node.54
> uv: 1.28.0
> zlib: 1.2.11
> brotli: 1.0.7
> ares: 1.15.0
> modules: 64
> nghttp2: 1.39.2
> napi: 4
> openssl: 1.1.1c
> icu: 64.2
> unicode: 12.1
> cldr: 35.1
> tz: 2019a
> 
> cat package.json
> {
> "name": "hexo-site",
> "version": "0.0.0",
> "private": true,
> "scripts": {
> "build": "hexo generate",
> "clean": "hexo clean",
> "deploy": "hexo deploy",
> "server": "hexo server"
> },
> "hexo": {
> "version": "4.2.0"
> },
> "dependencies": {
> "hexo": "^4.0.0",
> "hexo-generator-archive": "^1.0.0",
> "hexo-generator-category": "^1.0.0",
> "hexo-generator-index": "^1.0.0",
> "hexo-generator-tag": "^1.0.0",
> "hexo-renderer-ejs": "^1.0.0",
> "hexo-renderer-stylus": "^1.1.0",
> "hexo-renderer-marked": "^2.0.0",
> "hexo-server": "^1.0.0"
> }

这是我的版本，你可以参考下
$ hexo version
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.18363 win32 x64
node: 12.13.0
v8: 7.7.299.13-node.12
uv: 1.32.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 72
nghttp2: 1.39.2
napi: 5
llhttp: 1.1.4
http_parser: 2.8.0
openssl: 1.1.1d
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
